# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appearance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ppearance.proto\"\"\n\x11\x41ppearanceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"D\n\x12\x41ppearanceResponse\x12\x0f\n\x07\x63lasses\x18\x01 \x01(\x0c\x12\x0e\n\x06\x62\x62oxes\x18\x02 \x01(\x0c\x12\r\n\x05probs\x18\x03 \x01(\x0c\x32\x42\n\nAppearance\x12\x34\n\x07predict\x12\x12.AppearanceRequest\x1a\x13.AppearanceResponse\"\x00\x62\x06proto3')



_APPEARANCEREQUEST = DESCRIPTOR.message_types_by_name['AppearanceRequest']
_APPEARANCERESPONSE = DESCRIPTOR.message_types_by_name['AppearanceResponse']
AppearanceRequest = _reflection.GeneratedProtocolMessageType('AppearanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPEARANCEREQUEST,
  '__module__' : 'appearance_pb2'
  # @@protoc_insertion_point(class_scope:AppearanceRequest)
  })
_sym_db.RegisterMessage(AppearanceRequest)

AppearanceResponse = _reflection.GeneratedProtocolMessageType('AppearanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPEARANCERESPONSE,
  '__module__' : 'appearance_pb2'
  # @@protoc_insertion_point(class_scope:AppearanceResponse)
  })
_sym_db.RegisterMessage(AppearanceResponse)

_APPEARANCE = DESCRIPTOR.services_by_name['Appearance']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPEARANCEREQUEST._serialized_start=20
  _APPEARANCEREQUEST._serialized_end=54
  _APPEARANCERESPONSE._serialized_start=56
  _APPEARANCERESPONSE._serialized_end=124
  _APPEARANCE._serialized_start=126
  _APPEARANCE._serialized_end=192
# @@protoc_insertion_point(module_scope)
